### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by JonanekDev** [knisshoku/pvea#13]
Hi i tried this package and when i run code it returned 
```
Err: Error: unable to verify the first certificate
Err: Authentication failed.
```
How can i fix it?

**Comment by simonfrfr** [comment]
Can you give us more info on your configuration?

**Comment by MirSowasVonEgal** [comment]
Change the Top Lines of the pvea.js to:

`const Axios = require('axios')
const https = require('https')
const httpsAgent = new https.Agent({ rejectUnauthorized: false });
const axios = Axios.create({ httpsAgent })`

**Comment by knisshoku** [comment]
If you're having issues with your certificate not validating, it's probably not a valid cert.

I'd suggest using letsencrypt on your proxmox install, on 6.1 and higher it should be built-in to the software. 

I can look into adding a toggle in a config file or something alike for invalid certs, but it will be a while for me to get at that (I've been working overtime since I moved out to Nebraska)
